/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package console.java.views;

import console.java.controllers.JAdminController;
import console.java.entities.Admin;
import console.java.models.JModel;
import console.java.models.SessionAdmin;
import console.java.utilities.JUntilities;
import java.sql.SQLException;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author DongHo
 */
public class JMain extends javax.swing.JFrame {

     /**
      * Creates new form JMain
      */
     public JMain() {
	  initComponents();
     }

     /**
      * This method is called from within the constructor to initialize the
      * form. WARNING: Do NOT modify this code. The content of this method is
      * always regenerated by the Form Editor.
      */
     @SuppressWarnings("unchecked")
     // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
     private void initComponents() {

          jTabbedPane1 = new javax.swing.JTabbedPane();
          jPanel1 = new javax.swing.JPanel();
          jScrollPane1 = new javax.swing.JScrollPane();
          jTableAdmins = new javax.swing.JTable();
          jPanelAddNewAdmin = new javax.swing.JPanel();
          jLabel1 = new javax.swing.JLabel();
          txtAccount = new javax.swing.JTextField();
          jLabel2 = new javax.swing.JLabel();
          txtEmail = new javax.swing.JTextField();
          jLabel3 = new javax.swing.JLabel();
          btnAddNew = new javax.swing.JButton();
          jButton6 = new javax.swing.JButton();
          txtPasswordCharArray = new javax.swing.JPasswordField();
          errAccount = new javax.swing.JLabel();
          errEmail = new javax.swing.JLabel();
          errPass = new javax.swing.JLabel();
          errAddNewAdminResult = new javax.swing.JLabel();
          btnDel = new javax.swing.JButton();
          btnEdit = new javax.swing.JButton();
          btnAdd = new javax.swing.JButton();
          jLabel4 = new javax.swing.JLabel();
          txtKeyword = new javax.swing.JTextField();
          btnSearch = new javax.swing.JButton();
          showResult = new javax.swing.JLabel();
          jComboBoxOptionSearch = new javax.swing.JComboBox<>();
          jButton1 = new javax.swing.JButton();
          jPanel2 = new javax.swing.JPanel();

          setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
          addWindowListener(new java.awt.event.WindowAdapter() {
               public void windowOpened(java.awt.event.WindowEvent evt) {
                    formWindowOpened(evt);
               }
          });

          jTableAdmins.setModel(new javax.swing.table.DefaultTableModel(
               new Object [][] {

               },
               new String [] {
                    "ID", "Name", "Email"
               }
          ) {
               Class[] types = new Class [] {
                    java.lang.String.class, java.lang.String.class, java.lang.String.class
               };

               public Class getColumnClass(int columnIndex) {
                    return types [columnIndex];
               }
          });
          jScrollPane1.setViewportView(jTableAdmins);

          jPanelAddNewAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm Admin"));

          jLabel1.setText("Tài khoản");

          jLabel2.setText("Hòm thư");

          jLabel3.setText("Mật khẩu");

          btnAddNew.setText("Thêm mới");
          btnAddNew.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnAddNewActionPerformed(evt);
               }
          });

          jButton6.setText("Làm lại");
          jButton6.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton6ActionPerformed(evt);
               }
          });

          errAccount.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
          errAccount.setForeground(new java.awt.Color(255, 51, 0));

          errEmail.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
          errEmail.setForeground(new java.awt.Color(255, 0, 0));

          errPass.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
          errPass.setForeground(new java.awt.Color(255, 0, 0));

          errAddNewAdminResult.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
          errAddNewAdminResult.setForeground(new java.awt.Color(255, 0, 0));
          errAddNewAdminResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

          javax.swing.GroupLayout jPanelAddNewAdminLayout = new javax.swing.GroupLayout(jPanelAddNewAdmin);
          jPanelAddNewAdmin.setLayout(jPanelAddNewAdminLayout);
          jPanelAddNewAdminLayout.setHorizontalGroup(
               jPanelAddNewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanelAddNewAdminLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanelAddNewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jLabel1)
                         .addComponent(jLabel2)
                         .addComponent(jLabel3))
                    .addGap(18, 18, 18)
                    .addGroup(jPanelAddNewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                         .addComponent(errPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(errEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addComponent(errAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                         .addGroup(jPanelAddNewAdminLayout.createSequentialGroup()
                              .addComponent(btnAddNew)
                              .addGap(18, 18, 18)
                              .addComponent(jButton6))
                         .addComponent(txtEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                         .addComponent(txtAccount)
                         .addComponent(txtPasswordCharArray, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap(28, Short.MAX_VALUE))
               .addComponent(errAddNewAdminResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          );
          jPanelAddNewAdminLayout.setVerticalGroup(
               jPanelAddNewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanelAddNewAdminLayout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addGroup(jPanelAddNewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel1)
                         .addComponent(txtAccount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(errAccount)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanelAddNewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel2)
                         .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(errEmail)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelAddNewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                         .addComponent(jLabel3)
                         .addComponent(txtPasswordCharArray, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                    .addComponent(errPass)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanelAddNewAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(btnAddNew)
                         .addComponent(jButton6))
                    .addGap(18, 18, 18)
                    .addComponent(errAddNewAdminResult)
                    .addGap(30, 30, 30))
          );

          btnDel.setText("Xóa");
          btnDel.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnDelActionPerformed(evt);
               }
          });

          btnEdit.setText("Sửa");
          btnEdit.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnEditActionPerformed(evt);
               }
          });

          btnAdd.setText("Thêm");
          btnAdd.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnAddActionPerformed(evt);
               }
          });

          jLabel4.setText("Tìm kiếm");

          btnSearch.setText("Search");
          btnSearch.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    btnSearchActionPerformed(evt);
               }
          });

          showResult.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
          showResult.setForeground(new java.awt.Color(0, 0, 204));

          jComboBoxOptionSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo ID", "Theo Tên", "Theo Email" }));

          jButton1.setText("Tải lại danh sách");
          jButton1.addActionListener(new java.awt.event.ActionListener() {
               public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jButton1ActionPerformed(evt);
               }
          });

          javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
          jPanel1.setLayout(jPanel1Layout);
          jPanel1Layout.setHorizontalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addComponent(jScrollPane1)
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addComponent(jLabel4)
                              .addGap(18, 18, 18)
                              .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(jComboBoxOptionSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                              .addComponent(btnSearch)
                              .addGap(26, 26, 26)
                              .addComponent(showResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                         .addGroup(jPanel1Layout.createSequentialGroup()
                              .addComponent(jPanelAddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 224, Short.MAX_VALUE)
                              .addComponent(jButton1)
                              .addGap(18, 18, 18)
                              .addComponent(btnAdd)
                              .addGap(18, 18, 18)
                              .addComponent(btnEdit)
                              .addGap(18, 18, 18)
                              .addComponent(btnDel)))
                    .addContainerGap())
          );
          jPanel1Layout.setVerticalGroup(
               jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                         .addComponent(jLabel4)
                         .addComponent(txtKeyword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                         .addComponent(btnSearch)
                         .addComponent(showResult)
                         .addComponent(jComboBoxOptionSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                         .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                              .addComponent(btnDel)
                              .addComponent(btnEdit)
                              .addComponent(btnAdd)
                              .addComponent(jButton1))
                         .addComponent(jPanelAddNewAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(68, Short.MAX_VALUE))
          );

          jTabbedPane1.addTab("Quản lý Admins", jPanel1);

          javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
          jPanel2.setLayout(jPanel2Layout);
          jPanel2Layout.setHorizontalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 1005, Short.MAX_VALUE)
          );
          jPanel2Layout.setVerticalGroup(
               jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGap(0, 606, Short.MAX_VALUE)
          );

          jTabbedPane1.addTab("Quản lý Products", jPanel2);

          javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
          getContentPane().setLayout(layout);
          layout.setHorizontalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap())
          );
          layout.setVerticalGroup(
               layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap())
          );

          pack();
          setLocationRelativeTo(null);
     }// </editor-fold>//GEN-END:initComponents

     private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
	  // Thực hiện khi nhấn nút LÀM LẠI
	  txtAccount.setText("");
	  txtEmail.setText("");
	  txtPasswordCharArray.setText("");
     }//GEN-LAST:event_jButton6ActionPerformed

     private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
	  // THỰC HIỆN KHI BẮT ĐẦU MỞ CỬA SỔ
	  JAdminController.loadAdmins(jTableAdmins);
	  JAdminController.loadProducts();
	  jPanelAddNewAdmin.setVisible(false);
     }//GEN-LAST:event_formWindowOpened

     private void btnAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewActionPerformed
	  // Thực hiện khi nhấn nút thêm mới
	  if (txtAccount.getText().equals("")) {
	       errAccount.setText("Không để trống tài khoản!");
	       return;
	  } else {
	       errAccount.setText("");
	  }
	  if (!txtEmail.getText().matches("\\A([^@\\s]+)@((?:[-a-z0-9]+\\.)+[a-z]{2,})\\z")) {
	       errEmail.setText("Email trống hoặc không đúng định dạng!");
	       return;
	  } else {
	       errEmail.setText("");
	  }
	  if (txtPasswordCharArray.getPassword().length == 0) {
	       errPass.setText("Không để trống Mật khẩu!");
	       return;
	  } else {
	       errPass.setText("");
	  }
	  Admin admin = new Admin();
	  admin.setName(txtAccount.getText());
	  admin.setEmail(txtEmail.getText());
	  admin.setPassword(new String(txtPasswordCharArray.getPassword()));
	  try {
	       JModel.insert(admin, SessionAdmin.getIdToAction());
	  } catch (SQLException ex) {
	       JUntilities.alert("Lỗi: " + ex);
	  }
	  JAdminController.loadAdmins(jTableAdmins);
	  // reset
	  txtAccount.setText("");
	  txtEmail.setText("");
	  txtPasswordCharArray.setText("");
     }//GEN-LAST:event_btnAddNewActionPerformed

     private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
	  // TODO add your handling code here:
	  jPanelAddNewAdmin.setBorder(BorderFactory.createTitledBorder("Thêm Admin"));
	  btnAddNew.setText("Thêm mới");
	  SessionAdmin.setIdToAction(-1);
	  jPanelAddNewAdmin.setVisible(true);
     }//GEN-LAST:event_btnAddActionPerformed

     private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
	  // Hành động cho nút SỬA
	  int row = jTableAdmins.getSelectedRow();
	  if (row != -1) {
	       // bắt đầu panel sửa
	       jPanelAddNewAdmin.setBorder(BorderFactory.createTitledBorder("Sửa Admin"));
	       btnAddNew.setText("Sửa Admin");
	       jPanelAddNewAdmin.setVisible(true);
	       // lấy thông tin ra
	       TableModel tblModel = jTableAdmins.getModel();
	       SessionAdmin.setIdToAction(Integer.valueOf(tblModel.getValueAt(row, 0).toString()));
	       String name = tblModel.getValueAt(row, 1).toString();
	       String email = tblModel.getValueAt(row, 2).toString();
	       // thêm vào textField
	       txtAccount.setText(name);
	       txtEmail.setText(email);
	       
	       
	  } else {
	       JUntilities.alert("Vui lòng chọn để sửa!");
	  }
     }//GEN-LAST:event_btnEditActionPerformed

     private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
	  // TODO add your handling code here:
	  if (txtKeyword.getText().equals("")) {
	       JUntilities.alert("Hãy nhập từ khóa để tìm!");
	  } else {
	       showResult.setText("Tìm thấy " + JAdminController.searchAdmin(txtKeyword.getText(), jComboBoxOptionSearch.getSelectedIndex() + 1, jTableAdmins) + " kết quả!");
	  }
     }//GEN-LAST:event_btnSearchActionPerformed

     private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
	  // TODO add your handling code here:
	  int row = jTableAdmins.getSelectedRow();
	  if (row != -1) {
	       String value = jTableAdmins.getModel().getValueAt(row, 0).toString();
	       if (JOptionPane.showConfirmDialog(this, "Bạn có chắc là muốn xóa?") == 0) {
		    if (Integer.valueOf(value) == SessionAdmin.getId()) {
			 JUntilities.alert("Bạn không thể xóa chính mình!");
			 return;
		    }
		    try {
			 JModel.delete(new Admin(), Integer.valueOf(value));
			 JAdminController.loadAdmins(jTableAdmins);
		    } catch (SQLException ex) {
			 JUntilities.alert("Lỗi: " + ex);
		    }
	       }
	  } else {
	       JUntilities.alert("Vui lòng chọn để xóa!");
	  }
     }//GEN-LAST:event_btnDelActionPerformed

     private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
	  // TODO add your handling code here:
	  JAdminController.loadAdmins(jTableAdmins);
     }//GEN-LAST:event_jButton1ActionPerformed

     /**
      * @param args the command line arguments
      */
     public static void main(String args[]) {
	  /* Set the Nimbus look and feel */
	  //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	  /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	   */
	  try {
	       for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		    if ("Nimbus".equals(info.getName())) {
			 javax.swing.UIManager.setLookAndFeel(info.getClassName());
			 break;
		    }
	       }
	  } catch (ClassNotFoundException ex) {
	       java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	  } catch (InstantiationException ex) {
	       java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	  } catch (IllegalAccessException ex) {
	       java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	  } catch (javax.swing.UnsupportedLookAndFeelException ex) {
	       java.util.logging.Logger.getLogger(JMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	  }
	  //</editor-fold>

	  /* Create and display the form */
	  java.awt.EventQueue.invokeLater(new Runnable() {
	       public void run() {
		    new JMain().setVisible(true);
	       }
	  });
     }

     // Variables declaration - do not modify//GEN-BEGIN:variables
     private javax.swing.JButton btnAdd;
     private javax.swing.JButton btnAddNew;
     private javax.swing.JButton btnDel;
     private javax.swing.JButton btnEdit;
     private javax.swing.JButton btnSearch;
     private javax.swing.JLabel errAccount;
     private javax.swing.JLabel errAddNewAdminResult;
     private javax.swing.JLabel errEmail;
     private javax.swing.JLabel errPass;
     private javax.swing.JButton jButton1;
     private javax.swing.JButton jButton6;
     private javax.swing.JComboBox<String> jComboBoxOptionSearch;
     private javax.swing.JLabel jLabel1;
     private javax.swing.JLabel jLabel2;
     private javax.swing.JLabel jLabel3;
     private javax.swing.JLabel jLabel4;
     private javax.swing.JPanel jPanel1;
     private javax.swing.JPanel jPanel2;
     private javax.swing.JPanel jPanelAddNewAdmin;
     private javax.swing.JScrollPane jScrollPane1;
     private javax.swing.JTabbedPane jTabbedPane1;
     private javax.swing.JTable jTableAdmins;
     private javax.swing.JLabel showResult;
     private javax.swing.JTextField txtAccount;
     private javax.swing.JTextField txtEmail;
     private javax.swing.JTextField txtKeyword;
     private javax.swing.JPasswordField txtPasswordCharArray;
     // End of variables declaration//GEN-END:variables
}
